### ISSUE TITLE
Integrate CAN into EDGAR

### ISSUE THREAD

**Issue by jbaumgartl** [eclipse-opendut/opendut#28] opened 2024-01-11 15:07 UTC
Add the possibility to communicate via CAN between two ECUs. There are 3 scenarios:
1. ECUs are in a common network connected to the same EDGAR
2. ECUs are connected different EDGARs but the EDGARs are in the same network
3. There is no common network

**Comment by kKdH** [comment] 2024-01-11 18:27
duplicate of #4

**Closed by kKdH** 2024-01-11 18:27 UTC
Labels: resolution: duplicate, type: feature, component: edgar
